# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 07:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(verbose_name='Fecha de posteo')),
                ('text', models.TextField(verbose_name='Texto del mensaje')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que posteó el mensaje')),
            ],
            options={
                'ordering': ['-date_posted'],
                'verbose_name': 'mensaje',
                'verbose_name_plural': 'mensajes',
            },
        ),
    ]
