# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 04:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandMessage',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='identificador del mensaje')),
                ('date_posted', models.DateTimeField(verbose_name='fecha de posteo')),
                ('date_answered', models.DateTimeField(blank=True, null=True, verbose_name='fecha de respuesta')),
                ('request', models.TextField(verbose_name='mensaje enviado')),
                ('response', models.TextField(blank=True, null=True, verbose_name='mensaje recibido')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='usuario que envió el comando.')),
            ],
            options={
                'verbose_name': 'mensaje de comando',
                'ordering': ['-date_posted'],
                'verbose_name_plural': 'mensajes de comandos',
            },
        ),
    ]
