# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 21:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0002_commandmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commandmessage',
            options={'ordering': ['-date_posted'], 'verbose_name': 'command message', 'verbose_name_plural': 'command messages'},
        ),
        migrations.AddField(
            model_name='commandmessage',
            name='read',
            field=models.BooleanField(default=False, verbose_name='indicates whether the message was sent to the user.'),
        ),
        migrations.AlterField(
            model_name='commandmessage',
            name='date_answered',
            field=models.DateTimeField(blank=True, null=True, verbose_name='response date'),
        ),
        migrations.AlterField(
            model_name='commandmessage',
            name='date_posted',
            field=models.DateTimeField(verbose_name='posted date'),
        ),
        migrations.AlterField(
            model_name='commandmessage',
            name='request',
            field=models.TextField(verbose_name='the contents of the message sent'),
        ),
        migrations.AlterField(
            model_name='commandmessage',
            name='response',
            field=models.TextField(blank=True, null=True, verbose_name='the contents of the message received'),
        ),
        migrations.AlterField(
            model_name='commandmessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='user who sent the command.'),
        ),
        migrations.AlterField(
            model_name='commandmessage',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='message identifier'),
        ),
        migrations.AlterField(
            model_name='message',
            name='date_posted',
            field=models.DateTimeField(verbose_name='Posted date'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(verbose_name='Message text'),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to=settings.AUTH_USER_MODEL, verbose_name='User who posted the message.'),
        ),
    ]
